### ISSUE TITLE
Lazy extraction: extract minimap only

### ISSUE THREAD

**Issue by gajop** [Jazcash/spring-map-parser#2]
Right now we can only parse the entire map (height, texture, minimap, etc.), even if we only want to use a small portion of it.

In my current use case I'd like to get the minimap expediently, and I'd like to avoid having to parse everything else.
My plan is to load minimaps from all local user maps on the first load, and I'd like that to be fast.

**Comment by Jazcash** [comment]
I've added a flag to skip parsing the .smt (textureMap), which should significantly speed up parsing when set to true in v1.1.0:

`skipSmt: boolean` - defaults to false
